import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {flex: 1, backgroundColor: '#FFFFFF'},
    scrollContent: {
        paddingHorizontal: 14,
        paddingTop: 10,
        paddingBottom: 24,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    emptyContainer: {flex: 1, justifyContent: 'center', alignItems: 'center'},
    emptyText: {color: '#78909C'},
    documentTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1A1A1A',
        lineHeight: 22,
    },
    subHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    registeredNumber: {
        fontSize: 13,
        fontWeight: '600',
        color: '#1A1A1A',
        flex: 1,
    },

    createdDate: {
        fontSize: 11,
        color: '#777',
        fontStyle: 'italic',
    },
    lineDivider: {height: 1, backgroundColor: '#D3D3D3', marginBottom: 14},
    statusRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    statusLabel: {
        fontSize: 15,
        color: '#8A8A8A',
        fontWeight: '400',
    },

    statusValue: {
        fontSize: 15,
        color: '#43A047',
        fontWeight: '700',
    },
    iconActionContainer: {flexDirection: 'row', gap: 10},
    actionIconOrange: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FCE7C8',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionIconGreen: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#D8ECD6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    metaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    metaLabel: {
        fontSize: 12,
        color: '#9A9A9A',
    },
    metaValue: {
        color: '#2B2F33',
        fontWeight: '500',
    },
    blueInfoBox: {
        backgroundColor: '#EAF2FA',
        borderLeftWidth: 3,
        borderLeftColor: '#1E88E5',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 8,
        marginTop: 12,
        marginBottom: 14,
    },
    blueInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    blueInfoCol: {flex: 1},
    blueInfoColRight: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    infoLabel: {fontSize: 12, color: '#3F4A56', marginBottom: 2},
    infoValueBlue: {fontSize: 13, color: '#1E88E5', fontWeight: '500'},
    orangeBanner: {
        backgroundColor: '#FFF4E5',
        borderLeftWidth: 3,
        borderLeftColor: '#FF9800',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 6,
        marginBottom: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },

    orangeBannerText: {
        fontSize: 16,
        color: '#F39C12',
        fontStyle: 'italic',
        fontWeight: '500',
    },
    webviewContainer: {marginTop: 6, marginBottom: 12},
    documentContent: {
        width: Dimensions.get('window').width - 28,
        backgroundColor: '#FFFFFF',
    },
    attachedDocuments: {marginTop: 8},
    attachedDocumentsText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#222',
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
        marginBottom: 14,
    },
    requiredStar: {color: '#F44336'},
    signingSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#222',
        marginBottom: 10,
    },
    signingFileCardOuter: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#B3D4FC',
        padding: 10,
        marginBottom: 12,
        minHeight: 88,
    },
    signingFileInner: {
        backgroundColor: '#F5F5F5',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        minHeight: 72,
        flexDirection: 'row',
        alignItems: 'stretch',
    },
    signingCheckboxColumn: {
        alignItems: 'center',
        marginRight: 8,
        minWidth: 24,
    },
    signingCheckboxPlaceholder: {
        width: 21,
        height: 21,
    },
    signedStatusCheckbox: {
        width: 18,
        height: 18,
        borderRadius: 2,
        backgroundColor: '#B8B8B8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    signatureRowUnderCheckbox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 8,
    },
    signatureDot: {
        width: 18,
        height: 18,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    signatureDotRed: {
        backgroundColor: '#FFFFFF',
        borderWidth: 3,
        borderColor: '#FF4B4B',
    },
    signatureDotYellow: {
        backgroundColor: '#FFFFFF',
        borderWidth: 3,
        borderColor: '#FF9500',
    },
    signatureDotGreen: {
        backgroundColor: '#4CAF50',
    },
    signingFileMetaColumn: {
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        minHeight: 52,
        marginLeft: 8,
    },
    signingMetaSpacer: {
        flex: 1,
        minHeight: 4,
    },
    signingDownloadBtn: {
        paddingBottom: 2,
    },
    fileCard: {
        backgroundColor: '#F5F5F5',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },

    fileLeft: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        flex: 1,
    },

    filePreviewButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },

    fileRight: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 10,
    },

    checkboxWrap: {
        marginRight: 10,
        marginTop: 1,
    },

    fileNameWrap: {
        flex: 1,
        marginLeft: 10,
    },

    fileName: {
        fontSize: 14,
        color: '#3A3A3A',
        fontWeight: '400',
    },

    fileSize: {
        fontSize: 13,
        color: '#5F5F5F',
    },
    fileRightFileSize: {
        marginRight: 14,
    },

    signatureRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 8,
    },
    bottomActionsIncoming: {
        paddingHorizontal: 14,
        paddingTop: 8,
        paddingBottom: 10,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        gap: 8,
    },
    incomingActionButton: {
        height: 44,
        borderRadius: 8,
        backgroundColor: '#E3F3E4',
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    incomingActionButtonText: {
        color: '#4CAF50',
        fontSize: 16,
        fontWeight: '700',
    },
    incomingRejectButton: {
        height: 44,
        borderRadius: 8,
        backgroundColor: '#FFE1E1',
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    incomingRejectButtonText: {
        color: '#FF4B4B',
        fontSize: 16,
        fontWeight: '700',
    },
    bottomActions: {
        flexDirection: 'row',
        gap: 10,
        padding: 12,
        backgroundColor: '#FFFFFF',
    },
    rejectButton: {
        flex: 1,
        backgroundColor: '#FFE1E1',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        height: 44,
    },
    rejectButtonText: {color: '#FF4B4B', fontWeight: '700'},
    approveButton: {
        flex: 1,
        backgroundColor: '#FFF1DE',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        height: 44,
    },
    approveButtonText: {color: '#FF9500', fontWeight: '700'},
    disabledButton: {backgroundColor: '#D1D1D1'},
    disabledButtonText: {color: '#8A8A8A'},
    managementSignButton: {
        flex: 1,
        backgroundColor: '#E3F3E4',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        height: 44,
    },
    managementSignButtonText: {color: '#4CAF50', fontWeight: '700'},
    approveGreenButton: {backgroundColor: '#E3F3E4'},
    approveGreenButtonText: {color: '#4CAF50'},
    publishButton: {backgroundColor: '#FF9800'},
    archiveButton: {backgroundColor: '#4CAF50'},
    modalDivider: {
        height: 1,
        backgroundColor: '#E6E6E6',
        marginHorizontal: -14,
        marginBottom: 12,
    },
    modalCardIncoming: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 14,
    },
    modalTitleIncoming: {
        textAlign: 'center',
        fontSize: 32,
        fontWeight: '700',
        marginBottom: 10,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    modalCard: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 14,
    },
    modalTitle: {
        textAlign: 'center',
        fontSize: 28,
        fontWeight: '700',
        marginBottom: 12,
    },
    modalLabel: {color: '#4CAF50', fontWeight: '500', marginBottom: 6},
    modalInput: {
        backgroundColor: '#E8F3E8',
        borderRadius: 10,
        minHeight: 110,
        padding: 10,
        textAlignVertical: 'top',
    },
    modalActions: {flexDirection: 'row', gap: 14, marginTop: 16},
    backBtn: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#D3D3D3',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backBtnText: {fontWeight: '600'},
    confirmBtn: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#47B24A',
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmBtnText: {color: '#fff', fontWeight: '700'},
    mySignPendingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        zIndex: 99,
    },
    mySignPendingCard: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 14,
        paddingVertical: 22,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
    },
    mySignPendingText: {
        fontSize: 15,
        color: '#2B2F33',
        textAlign: 'center',
        fontWeight: '500',
    },
    publishConfirmBtn: {backgroundColor: '#47B24A'},
});

export default styles;
