import { StyleSheet } from 'react-native';

const editorStyles = StyleSheet.create({
    editorContainer: {
        height: 230,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#D3D5DB',
        backgroundColor: '#FFF',
        overflow: 'hidden',
        marginTop: 8,
        marginBottom: 12,
    },
    editorToolbar: {
        height: 42,
        backgroundColor: '#F8F9FB',
        borderBottomWidth: 1,
        borderBottomColor: '#D7DAE0',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 10,
        position: 'relative',
        zIndex: 10,
    },
    toolbarIconBtn: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    toolbarDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#D7DAE0',
        marginHorizontal: 8,
    },
    toolbarDropdown: {
        height: 28,
        minWidth: 100,
        backgroundColor: '#ECEFF3',
        borderRadius: 4,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
    },
    toolbarDropdownText: { fontSize: 14, color: '#3D495A', fontWeight: '500' },
    toolbarStrong: { fontSize: 18, fontWeight: '700', color: '#2E3747' },
    toolbarItalic: { fontSize: 18, fontStyle: 'italic', color: '#2E3747' },
    toolbarAButton: {
        height: 28,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    toolbarUnderline: {
        fontSize: 18,
        color: '#2E3747',
        textDecorationLine: 'underline',
    },
    menuBox: {
        position: 'absolute',
        top: 48,
        left: 70,
        width: 150,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#D8DCE3',
        borderRadius: 6,
        zIndex: 20,
        elevation: 5,
    },
    menuItem: { paddingHorizontal: 10, paddingVertical: 8 },
    menuText: { fontSize: 13, color: '#2F3A4A' },
    colorMenu: {
        position: 'absolute',
        top: 48,
        right: 12,
        width: 132,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#D8DCE3',
        borderRadius: 6,
        zIndex: 22,
        elevation: 6,
        padding: 8,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    colorDot: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 1,
        borderColor: '#CDD2DA',
    },
    editorBody: {
        flex: 1,
        borderTopWidth: 1,
        borderTopColor: '#D3D5DB',
        backgroundColor: '#FFF',
        overflow: 'hidden',
    },
    editorWarmup: { flex: 1, backgroundColor: '#FFF' },
    webview: { flex: 1, backgroundColor: '#FFF' },
});

export default editorStyles;
