import { StyleSheet } from 'react-native';

const formStyles = StyleSheet.create({
    createHeader: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#DBDBDB',
        marginHorizontal: -12,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    createTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#161616',
        flex: 1,
        marginRight: 12,
    },
    createReset: { fontSize: 13, color: '#66BB6A' },
    createScroll: { paddingBottom: 12, paddingTop: 12 },
    separator: {
        borderBottomWidth: 1,
        borderBottomColor: '#8CC7FF',
        borderStyle: 'dashed',
        marginTop: 10,
        marginBottom: 10,
    },
    blockTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2196F3',
        marginTop: 4,
        marginBottom: 8,
    },
    blockHint: {
        fontSize: 13,
        color: '#8D8D8D',
        fontStyle: 'italic',
        marginBottom: 4,
    },
    mutedHint: { color: '#777', fontStyle: 'italic' },
    fieldLabel: { fontSize: 13, color: '#222', marginBottom: 5, marginTop: 8 },
    required: { color: '#F05A5A' },
    inputWrap: {
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 6,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 10,
    },
    inputWrapFocused: { borderColor: '#4CAF50', backgroundColor: '#FFFFFF' },
    inputWrapError: { borderColor: '#FF4D4F' },
    input: {
        height: 38,
        fontSize: 13,
        color: '#222',
        paddingVertical: 0,
        paddingLeft: 2,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    row: { flexDirection: 'row', gap: 8 },
    half: { flex: 1 },
    dropdownWrap: { position: 'relative' },
    select: {
        height: 38,
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 6,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 10,
        alignItems: 'center',
        justifyContent: 'space-between',
        flexDirection: 'row',
    },
    selectFocused: { borderColor: '#4CAF50', backgroundColor: '#FFFFFF' },
    selectText: { fontSize: 13, color: '#5A5A5A', flex: 1 },
    fieldError: {
        color: '#FF4D4F',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'right',
    },
    fieldErrorLeft: {
        color: '#FF4D4F',
        fontSize: 12,
        marginTop: -4,
        marginBottom: 8,
        textAlign: 'left',
    },
    receiverRow: {
        height: 34,
        borderRadius: 6,
        backgroundColor: '#E9E9E9',
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    receiverLabel: { fontSize: 13, color: '#8B8B8B' },
    receiverValue: { fontSize: 13, color: '#1E88E5', fontWeight: '500' },
    uploadSign: {
        minHeight: 40,
        borderWidth: 1,
        borderColor: '#9BD69E',
        borderStyle: 'dashed',
        borderRadius: 6,
        backgroundColor: '#EAF7EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    uploadAttach: {
        minHeight: 40,
        borderWidth: 1,
        borderColor: '#F3B260',
        borderStyle: 'dashed',
        borderRadius: 6,
        backgroundColor: '#FFF3E6',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    uploadLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
        marginRight: 8,
    },
    uploadSignText: { fontSize: 13, color: '#555', flexShrink: 1 },
    uploadAttachText: { fontSize: 13, color: '#555', flexShrink: 1 },
    fileRow: {
        height: 40,
        backgroundColor: '#EFEFEF',
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    fileLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    fileName: { marginLeft: 8, color: '#4A4A4A', fontSize: 13, flex: 1 },
    fileRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    fileSize: { color: '#777', fontSize: 12 },
    multiItemRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    bottomActions: {
        height: 78,
        borderTopWidth: 1,
        borderTopColor: '#DADADA',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        paddingTop: 10,
        backgroundColor: '#EFEFEF',
    },
    bottomActionsSingle: {
        height: 70,
        borderTopWidth: 1,
        borderTopColor: '#DADADA',
        justifyContent: 'center',
        backgroundColor: '#EFEFEF',
        paddingHorizontal: 10,
    },
    btnDraft: {
        flex: 1,
        height: 46,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#9B9B9B',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8F8F8',
    },
    btnDraftText: { fontSize: 16, color: '#8D8D8D', fontWeight: '500' },
    btnSubmit: {
        flex: 1.2,
        height: 46,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4CAF50',
    },
    btnSubmitSingle: {
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4CAF50',
    },
    btnSubmitText: { fontSize: 16, color: '#FFF', fontWeight: '600' },
});

export default formStyles;
