import { StyleSheet } from 'react-native';

const listStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EFEFEF',
        paddingHorizontal: 12,
        paddingTop: 8,
    },
    flexOne: { flex: 1 },
    headerRow: {
        height: 44,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    headerIconBtn: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: { fontSize: 20, fontWeight: '700', color: '#1E1E1E' },
    headerCreateButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#4CAF50',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 4,
    },
    headerCreateButtonDisabled: { opacity: 0.6 },
    chipRow: { marginTop: 12, marginBottom: 8 },
    chipScroll: { flexGrow: 0 },
    chipRowContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingRight: 8,
    },
    chip: {
        backgroundColor: '#D8D8D8',
        borderRadius: 999,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginRight: 6,
    },
    chipActive: { backgroundColor: '#54B35A' },
    chipText: { fontSize: 12, color: '#555', fontWeight: '500' },
    chipTextActive: { color: '#FFF' },
    totalText: { marginTop: 2, marginBottom: 10, fontSize: 16, color: '#666' },
    listContent: { paddingBottom: 20 },
    // Card styles
    card: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#DBDBDB',
        marginBottom: 10,
    },
    cardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1F1F1F',
        flex: 1,
        marginRight: 8,
    },
    statusTag: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusText: { fontSize: 11, fontWeight: '600' },
    metaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#EFEFEF',
        paddingBottom: 8,
    },
    metaLeft: { fontSize: 14, color: '#4D4D4D' },
    metaRight: { fontSize: 14, color: '#8E8E8E' },
    bottomRow: {
        paddingTop: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    stepText: { fontSize: 14, color: '#666' },
    actionRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    updateActionButton: {
        minHeight: 26,
        borderRadius: 999,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#4CAF50',
        backgroundColor: '#EAF7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    updateActionButtonDisabled: { opacity: 0.6 },
    updateActionButtonText: {
        fontSize: 12,
        color: '#2D8F31',
        fontWeight: '600',
    },
    // Search/filter (kept for backward-compat; also in shared SearchBar)
    searchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    searchBox: {
        flex: 1,
        height: 42,
        backgroundColor: '#FFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#D7D7D7',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    searchInput: { flex: 1, color: '#222', fontSize: 14, paddingVertical: 0 },
    filterButton: {
        width: 36,
        height: 36,
        borderWidth: 1,
        borderColor: '#D7D7D7',
        borderRadius: 8,
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default listStyles;
