import { StyleSheet } from 'react-native';

const modalStyles = StyleSheet.create({
    dropdownModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.2)',
        justifyContent: 'center',
        paddingHorizontal: 18,
    },
    dropdownModalBackdrop: { ...StyleSheet.absoluteFillObject },
    dropdownModalCard: {
        width: '100%',
        maxHeight: 420,
        backgroundColor: '#FFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DCDCDC',
        overflow: 'hidden',
    },
    dropdownModalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1E1E1E',
        paddingHorizontal: 12,
        paddingTop: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    dropdownSearchWrap: {
        height: 42,
        marginHorizontal: 10,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: '#D9DDE3',
        borderRadius: 8,
        backgroundColor: '#F8F9FB',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    dropdownSearchInput: {
        flex: 1,
        height: 40,
        marginLeft: 8,
        color: '#222',
        fontSize: 14,
        paddingVertical: 0,
    },
    dropdownSearchClear: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dropdownList: { maxHeight: 360 },
    dropdownMenu: {
        marginTop: 4,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#DCDCDC',
        borderRadius: 10,
        overflow: 'hidden',
    },
    dropdownItem: {
        minHeight: 44,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        justifyContent: 'center',
    },
    dropdownItemContent: { flex: 1 },
    dropdownItemText: { fontSize: 14, color: '#333' },
    dropdownItemSubText: { fontSize: 12, color: '#8A8A8A', marginTop: 2 },
    dropdownStateRow: {
        minHeight: 72,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: 12,
    },
    dropdownStateText: { fontSize: 14, color: '#777', textAlign: 'center' },
    // Date picker modal
    dateModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 18,
    },
    dateModalCard: {
        width: '100%',
        backgroundColor: '#FFF',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 12,
    },
    dateModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E1E1E',
        marginBottom: 10,
    },
    dateModalInput: {
        height: 44,
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 8,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 12,
        fontSize: 16,
        color: '#222',
    },
    dateModalError: { color: '#FF4D4F', fontSize: 12, marginTop: 6 },
    dateQuickRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
    dateQuickButton: {
        flex: 1,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#EAF2FA',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateQuickText: { fontSize: 14, color: '#1E88E5', fontWeight: '600' },
    dateModalActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
    dateCancelButton: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#D7D7D7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateCancelText: { fontSize: 16, color: '#444', fontWeight: '600' },
    dateApplyButton: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#4CAF50',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateApplyText: { fontSize: 16, color: '#FFF', fontWeight: '700' },
    // Delete/confirm modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBox: {
        width: '88%',
        backgroundColor: '#FFF',
        borderRadius: 18,
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 14,
    },
    modalTitle: {
        fontSize: 34,
        color: '#1E1E1E',
        textAlign: 'center',
        fontWeight: '700',
        marginBottom: 8,
    },
    modalMessage: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        marginBottom: 10,
    },
    modalDocTitle: {
        fontSize: 14,
        color: '#222',
        textAlign: 'center',
        fontWeight: '700',
        marginBottom: 10,
    },
    modalWarningWrap: {
        backgroundColor: '#FFE8E8',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 14,
    },
    modalWarningText: {
        fontSize: 13,
        color: '#FF6B6B',
        textAlign: 'center',
        fontWeight: '500',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    modalBtnGhost: {
        flex: 1,
        backgroundColor: '#D7D7D7',
        borderRadius: 10,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnGhostText: { color: '#444', fontSize: 18, fontWeight: '600' },
    modalBtnDanger: {
        flex: 1,
        backgroundColor: '#FF4A43',
        borderRadius: 10,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnDangerText: { color: '#FFF', fontSize: 18, fontWeight: '700' },
});

export default modalStyles;
