# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# node_require('react-native/scripts/react_native_pods.rb')
# node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => static
end

target 'CF15_OFFICE_APPLICATION' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add this block to fix issues with Apple Silicon and glog
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('glog')
        def pod.build_type;
          # Uncomment one line depending on the chip (Intel or Apple Silicon)
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Setting chung
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.2'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end

    # Fix fmt-dummy.m (nếu còn lỗi)
    fmt_target = installer.pods_project.targets.find { |t| t.name == 'fmt' }
    if fmt_target
      fmt_target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end

      # Fix dummy file
      fmt_target.source_build_phase.files.each do |build_file|
        if build_file.file_ref && build_file.file_ref.path&.end_with?('fmt-dummy.m')
          build_file.settings ||= {}
          build_file.settings['COMPILER_FLAGS'] = ''
        end
      end
    end
  end
end
