import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#EFEFEF', paddingHorizontal: 12, paddingTop: 8 },
  headerRow: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  headerIconBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 28, fontWeight: '700', color: '#1E1E1E' },
  headerCreateButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#4CAF50', alignItems: 'center', justifyContent: 'center', marginRight: 4 },
  headerCreateButtonDisabled: { opacity: 0.6 },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  searchBox: { flex: 1, height: 42, backgroundColor: '#FFF', borderRadius: 10, borderWidth: 1, borderColor: '#D7D7D7', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10 },
  searchInput: { flex: 1, color: '#222', fontSize: 14, paddingVertical: 0 },
  filterButton: { width: 36, height: 36, borderWidth: 1, borderColor: '#D7D7D7', borderRadius: 8, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  chipRow: { marginTop: 12, marginBottom: 8 },
  chipScroll: { flexGrow: 0 },
  chipRowContent: { flexDirection: 'row', alignItems: 'center', paddingRight: 8 },
  chip: { backgroundColor: '#D8D8D8', borderRadius: 999, paddingVertical: 5, paddingHorizontal: 10, marginRight: 6 },
  chipActive: { backgroundColor: '#54B35A' },
  chipText: { fontSize: 12, color: '#555', fontWeight: '500' },
  chipTextActive: { color: '#FFF' },
  totalText: { marginTop: 2, marginBottom: 10, fontSize: 16, color: '#666' },
  listContent: { paddingBottom: 20 },
  card: { backgroundColor: '#FFF', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 12, borderWidth: 1, borderColor: '#DBDBDB', marginBottom: 10 },
  cardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#1F1F1F', flex: 1, marginRight: 8 },
  statusTag: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  statusText: { fontSize: 11, fontWeight: '600' },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#EFEFEF', paddingBottom: 8 },
  metaLeft: { fontSize: 14, color: '#4D4D4D' },
  metaRight: { fontSize: 14, color: '#8E8E8E' },
  bottomRow: { paddingTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  stepText: { fontSize: 14, color: '#666' },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  createHeader: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#DBDBDB', marginHorizontal: -12, paddingHorizontal: 12 },
  createTitle: { fontSize: 30, fontWeight: '700', color: '#161616' },
  createReset: { fontSize: 14, color: '#66BB6A' },
  createScrollView: { flex: 1 },
  createScroll: { paddingBottom: 12, paddingTop: 12, flexGrow: 1 },
  createScrollKeyboard: { paddingBottom: 96 },
  fieldLabel: { fontSize: 17, color: '#222', marginBottom: 6, marginTop: 8 },
  required: { color: '#F05A5A' },
  inputWrap: { borderWidth: 1, borderColor: '#BFBFBF', borderRadius: 10, backgroundColor: '#F7F7F7', paddingHorizontal: 12 },
  inputWrapError: { borderColor: '#FF4D4F' },
  input: { height: 44, fontSize: 14, color: '#222', paddingVertical: 0, paddingLeft: 2, textAlignVertical: 'center', includeFontPadding: false },
  row: { flexDirection: 'row', gap: 8, zIndex: 20 },
  half: { flex: 1, position: 'relative', zIndex: 20 },
  fullDropdownWrap: { position: 'relative', zIndex: 19 },
  select: { height: 44, borderWidth: 1, borderColor: '#BFBFBF', borderRadius: 10, backgroundColor: '#F7F7F7', paddingHorizontal: 12, alignItems: 'center', justifyContent: 'space-between', flexDirection: 'row' },
  selectText: { fontSize: 14, color: '#5A5A5A' },
  dropdownMenu: { position: 'absolute', top: 46, left: 0, right: 0, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#DCDCDC', borderRadius: 10, maxHeight: 220, zIndex: 50, elevation: 8 },
  dropdownItem: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  dropdownItemText: { fontSize: 14, color: '#333' },
  fieldError: { color: '#FF4D4F', fontSize: 12, marginTop: 4, textAlign: 'right' },
  fieldErrorLeft: { color: '#FF4D4F', fontSize: 12, marginTop: -4, marginBottom: 8, textAlign: 'left' },
  receiverRow: { height: 42, borderRadius: 8, backgroundColor: '#E9E9E9', marginTop: 10, marginBottom: 10, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  receiverLabel: { fontSize: 13, color: '#8B8B8B' },
  receiverValue: { fontSize: 13, color: '#1E88E5', fontWeight: '500' },
  uploadSign: { minHeight: 44, borderWidth: 1, borderColor: '#9BD69E', borderStyle: 'dashed', borderRadius: 10, backgroundColor: '#EAF7EB', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, marginBottom: 10 },
  uploadAttach: { minHeight: 44, borderWidth: 1, borderColor: '#F3B260', borderStyle: 'dashed', borderRadius: 10, backgroundColor: '#FFF3E6', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, marginBottom: 10 },
  uploadLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1, marginRight: 8 },
  uploadSignText: { fontSize: 13, color: '#555', flexShrink: 1 },
  uploadAttachText: { fontSize: 13, color: '#555', flexShrink: 1 },
  fileRow: { height: 40, backgroundColor: '#EFEFEF', borderRadius: 8, paddingHorizontal: 10, marginBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  fileLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 8 },
  fileName: { marginLeft: 8, color: '#4A4A4A', fontSize: 13, flex: 1 },
  fileRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fileSize: { color: '#777', fontSize: 12 },
  editorToolbar: {
    height: 42,
    backgroundColor: '#F8F9FB',
    borderBottomWidth: 1,
    borderBottomColor: '#D7DAE0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    position: 'relative',
    zIndex: 10,
  },
  toolbarIconBtn: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  toolbarSpacer: { flex: 1 },
  toolbarDropdown: { height: 28, minWidth: 100, backgroundColor: '#ECEFF3', borderRadius: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10 },
  toolbarDropdownText: { fontSize: 14, color: '#3D495A', fontWeight: '500' },
  toolbarText: { fontSize: 13, color: '#3D495A' },
  toolbarStrong: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2E3747',
  },
  toolbarItalic: {
    fontSize: 18,
    fontStyle: 'italic',
    color: '#2E3747',
  },
  toolbarAButton: { height: 28, flexDirection: 'row', alignItems: 'center', gap: 2 },
  toolbarUnderline: {
    fontSize: 18,
    color: '#2E3747',
    textDecorationLine: 'underline',
  },
  menuBox: { position: 'absolute', top: 48, left: 70, width: 150, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#D8DCE3', borderRadius: 6, zIndex: 20, elevation: 5 },
  fontMenuBox: { position: 'absolute', top: 48, left: 110, width: 160, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#D8DCE3', borderRadius: 6, zIndex: 21, elevation: 6 },
  menuItem: { paddingHorizontal: 10, paddingVertical: 8 },
  menuText: { fontSize: 13, color: '#2F3A4A' },
  menuDivider: { height: 1, backgroundColor: '#EBEDF0' },
  colorMenu: { position: 'absolute', top: 48, right: 12, width: 132, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#D8DCE3', borderRadius: 6, zIndex: 22, elevation: 6, padding: 8, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  colorDot: { width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: '#CDD2DA' },
  editorBody: { flex: 1, borderTopWidth: 1, borderTopColor: '#D3D5DB', backgroundColor: '#FFF', overflow: 'hidden' },
  webview: { flex: 1, backgroundColor: '#FFF' },
  bottomActions: { height: 78, borderTopWidth: 1, borderTopColor: '#DADADA', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingTop: 10, backgroundColor: '#EFEFEF' },
  formActionDisabled: { opacity: 0.7 },
  webEditorContainer: { height: 220 },
  btnDraft: { flex: 1, height: 46, borderRadius: 24, borderWidth: 1, borderColor: '#9B9B9B', alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8F8F8' },
  btnDraftText: { fontSize: 16, color: '#8D8D8D', fontWeight: '500' },
  btnSubmit: { flex: 1.2, height: 46, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: '#4CAF50' },
  btnSubmitText: { fontSize: 16, color: '#FFF', fontWeight: '600' },
  editorContainer: {
    height: 220,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D3D5DB',
    backgroundColor: '#FFF',
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 12,
  },
  toolbarDivider: { width: 1, height: 24, backgroundColor: '#D7DAE0', marginHorizontal: 8 },
});

export default styles;
