export type ScreenName =
    /* ONBOARDING */
    | 'INDEX'
    | 'LOGIN'
    | 'AUTOMATIC_TRACING'
    /* HOME */
    | 'MAIN'
    | 'LISTNOTIFICATION'
    | 'DOCUMENT'
    | 'DETAILDOCUMENTS'
    | 'BROWSEJOBS'
    | 'GARDENINFO'
    | 'GARDENDECLARE'
    | 'DIRECT_EXPORT_FILLED_GAS_TANK'
    | 'WAREHOUSE_EXPORT_FILLED_GAS_TANK'
    | 'DIRECT_EXPORT_GAS_TANK'
    | 'WAREHOUSE_EXPORT_GAS_TANK'
    | 'FULL_CYLINDER_RETURN'
    | 'IMPORT_TANK'
    | 'UPDATE_EXPIRED_AUDIT'
    | 'EXPORT_PRODUCT'
    | 'SELLING'
    | 'STATISTIC'
    /* USER */
    | 'PROFILE'
    | 'UPDATE_PASSWORD'
    | 'NOTIFICATION'
    | 'FEEDBACK'
    | 'FEEDBACK1'
    | 'NEWS'
    | 'NEWS1'
    /* GLOBAL */
    | 'CAMERA_SCANNER'
    | 'MANUAL_SEARCHING'
    | 'GAS_TANK_DETAIL'
    | 'SCANNED_GAS_TANK'
    /* SUB-SCREENS */
    | 'LOADING'
    | 'ERROR';
