import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EFEFEF',
        paddingHorizontal: 12,
        paddingTop: 8,
    },
    flexOne: {flex: 1},
    headerRow: {
        height: 44,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    headerIconBtn: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {fontSize: 20, fontWeight: '700', color: '#1E1E1E'},
    headerCreateButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#4CAF50',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 4,
    },
    headerCreateButtonDisabled: {opacity: 0.6},
    searchRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
    searchBox: {
        flex: 1,
        height: 42,
        backgroundColor: '#FFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#D7D7D7',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    searchInput: {flex: 1, color: '#222', fontSize: 14, paddingVertical: 0},
    filterButton: {
        width: 36,
        height: 36,
        borderWidth: 1,
        borderColor: '#D7D7D7',
        borderRadius: 8,
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    chipRow: {marginTop: 12, marginBottom: 8},
    chipScroll: {flexGrow: 0},
    chipRowContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingRight: 8,
    },
    chip: {
        backgroundColor: '#D8D8D8',
        borderRadius: 999,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginRight: 6,
    },
    chipActive: {backgroundColor: '#54B35A'},
    chipText: {fontSize: 12, color: '#555', fontWeight: '500'},
    chipTextActive: {color: '#FFF'},
    totalText: {marginTop: 2, marginBottom: 10, fontSize: 16, color: '#666'},
    listContent: {paddingBottom: 20},
    card: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#DBDBDB',
        marginBottom: 10,
    },
    cardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1F1F1F',
        flex: 1,
        marginRight: 8,
    },
    statusTag: {borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3},
    statusText: {fontSize: 11, fontWeight: '600'},
    metaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#EFEFEF',
        paddingBottom: 8,
    },
    metaLeft: {fontSize: 14, color: '#4D4D4D'},
    metaRight: {fontSize: 14, color: '#8E8E8E'},
    bottomRow: {
        paddingTop: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    stepText: {fontSize: 14, color: '#666'},
    actionRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
    updateActionButton: {
        minHeight: 26,
        borderRadius: 999,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#4CAF50',
        backgroundColor: '#EAF7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    updateActionButtonDisabled: {
        opacity: 0.6,
    },
    updateActionButtonText: {
        fontSize: 12,
        color: '#2D8F31',
        fontWeight: '600',
    },

    createHeader: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#DBDBDB',
        marginHorizontal: -12,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    createTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#161616',
        flex: 1,
        marginRight: 12,
    },
    createReset: {fontSize: 13, color: '#66BB6A'},
    createScroll: {paddingBottom: 12, paddingTop: 12},
    separator: {
        borderBottomWidth: 1,
        borderBottomColor: '#8CC7FF',
        borderStyle: 'dashed',
        marginTop: 10,
        marginBottom: 10,
    },
    blockTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2196F3',
        marginTop: 4,
        marginBottom: 8,
    },
    blockHint: {
        fontSize: 13,
        color: '#8D8D8D',
        fontStyle: 'italic',
        marginBottom: 4,
    },
    mutedHint: {color: '#777', fontStyle: 'italic'},

    fieldLabel: {fontSize: 13, color: '#222', marginBottom: 5, marginTop: 8},
    required: {color: '#F05A5A'},
    inputWrap: {
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 6,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 10,
    },
    inputWrapFocused: {borderColor: '#4CAF50', backgroundColor: '#FFFFFF'},
    inputWrapError: {borderColor: '#FF4D4F'},
    input: {
        height: 38,
        fontSize: 13,
        color: '#222',
        paddingVertical: 0,
        paddingLeft: 2,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    row: {flexDirection: 'row', gap: 8},
    half: {flex: 1},
    dropdownWrap: {position: 'relative'},
    select: {
        height: 38,
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 6,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 10,
        alignItems: 'center',
        justifyContent: 'space-between',
        flexDirection: 'row',
    },
    selectFocused: {borderColor: '#4CAF50', backgroundColor: '#FFFFFF'},
    selectText: {fontSize: 13, color: '#5A5A5A', flex: 1},
    dropdownModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.2)',
        justifyContent: 'center',
        paddingHorizontal: 18,
    },
    dropdownModalBackdrop: {...StyleSheet.absoluteFillObject},
    dropdownModalCard: {
        width: '100%',
        maxHeight: 420,
        backgroundColor: '#FFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DCDCDC',
        overflow: 'hidden',
    },
    dropdownModalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1E1E1E',
        paddingHorizontal: 12,
        paddingTop: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    dropdownSearchWrap: {
        height: 42,
        marginHorizontal: 10,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: '#D9DDE3',
        borderRadius: 8,
        backgroundColor: '#F8F9FB',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    dropdownSearchInput: {
        flex: 1,
        height: 40,
        marginLeft: 8,
        color: '#222',
        fontSize: 14,
        paddingVertical: 0,
    },
    dropdownSearchClear: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dropdownList: {maxHeight: 360},
    dropdownMenu: {
        marginTop: 4,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#DCDCDC',
        borderRadius: 10,
        overflow: 'hidden',
    },
    dropdownItem: {
        minHeight: 44,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        justifyContent: 'center',
    },
    dropdownItemContent: {flex: 1},
    dropdownItemText: {fontSize: 14, color: '#333'},
    dropdownItemSubText: {fontSize: 12, color: '#8A8A8A', marginTop: 2},
    dropdownStateRow: {
        minHeight: 72,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: 12,
    },
    dropdownStateText: {fontSize: 14, color: '#777', textAlign: 'center'},
    multiItemRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
    fieldError: {
        color: '#FF4D4F',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'right',
    },
    fieldErrorLeft: {
        color: '#FF4D4F',
        fontSize: 12,
        marginTop: -4,
        marginBottom: 8,
        textAlign: 'left',
    },

    receiverRow: {
        height: 34,
        borderRadius: 6,
        backgroundColor: '#E9E9E9',
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    receiverLabel: {fontSize: 13, color: '#8B8B8B'},
    receiverValue: {fontSize: 13, color: '#1E88E5', fontWeight: '500'},

    uploadSign: {
        minHeight: 40,
        borderWidth: 1,
        borderColor: '#9BD69E',
        borderStyle: 'dashed',
        borderRadius: 6,
        backgroundColor: '#EAF7EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    uploadAttach: {
        minHeight: 40,
        borderWidth: 1,
        borderColor: '#F3B260',
        borderStyle: 'dashed',
        borderRadius: 6,
        backgroundColor: '#FFF3E6',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        marginBottom: 10,
    },
    uploadLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
        marginRight: 8,
    },
    uploadSignText: {fontSize: 13, color: '#555', flexShrink: 1},
    uploadAttachText: {fontSize: 13, color: '#555', flexShrink: 1},

    fileRow: {
        height: 40,
        backgroundColor: '#EFEFEF',
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    fileLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    fileName: {marginLeft: 8, color: '#4A4A4A', fontSize: 13, flex: 1},
    fileRight: {flexDirection: 'row', alignItems: 'center', gap: 8},
    fileSize: {color: '#777', fontSize: 12},

    editorContainer: {
        height: 230,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#D3D5DB',
        backgroundColor: '#FFF',
        overflow: 'hidden',
        marginTop: 8,
        marginBottom: 12,
    },
    editorToolbar: {
        height: 42,
        backgroundColor: '#F8F9FB',
        borderBottomWidth: 1,
        borderBottomColor: '#D7DAE0',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 10,
        position: 'relative',
        zIndex: 10,
    },
    toolbarIconBtn: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    toolbarDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#D7DAE0',
        marginHorizontal: 8,
    },
    toolbarDropdown: {
        height: 28,
        minWidth: 100,
        backgroundColor: '#ECEFF3',
        borderRadius: 4,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
    },
    toolbarDropdownText: {fontSize: 14, color: '#3D495A', fontWeight: '500'},
    toolbarStrong: {fontSize: 18, fontWeight: '700', color: '#2E3747'},
    toolbarItalic: {fontSize: 18, fontStyle: 'italic', color: '#2E3747'},
    toolbarAButton: {
        height: 28,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    toolbarUnderline: {
        fontSize: 18,
        color: '#2E3747',
        textDecorationLine: 'underline',
    },
    menuBox: {
        position: 'absolute',
        top: 48,
        left: 70,
        width: 150,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#D8DCE3',
        borderRadius: 6,
        zIndex: 20,
        elevation: 5,
    },
    menuItem: {paddingHorizontal: 10, paddingVertical: 8},
    menuText: {fontSize: 13, color: '#2F3A4A'},
    colorMenu: {
        position: 'absolute',
        top: 48,
        right: 12,
        width: 132,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#D8DCE3',
        borderRadius: 6,
        zIndex: 22,
        elevation: 6,
        padding: 8,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    colorDot: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 1,
        borderColor: '#CDD2DA',
    },
    editorBody: {
        flex: 1,
        borderTopWidth: 1,
        borderTopColor: '#D3D5DB',
        backgroundColor: '#FFF',
        overflow: 'hidden',
    },
    editorWarmup: {flex: 1, backgroundColor: '#FFF'},
    webview: {flex: 1, backgroundColor: '#FFF'},

    bottomActions: {
        height: 78,
        borderTopWidth: 1,
        borderTopColor: '#DADADA',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        paddingTop: 10,
        backgroundColor: '#EFEFEF',
    },
    bottomActionsSingle: {
        height: 70,
        borderTopWidth: 1,
        borderTopColor: '#DADADA',
        justifyContent: 'center',
        backgroundColor: '#EFEFEF',
        paddingHorizontal: 10,
    },
    btnDraft: {
        flex: 1,
        height: 46,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#9B9B9B',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8F8F8',
    },
    btnDraftText: {fontSize: 16, color: '#8D8D8D', fontWeight: '500'},
    btnSubmit: {
        flex: 1.2,
        height: 46,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4CAF50',
    },
    btnSubmitSingle: {
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4CAF50',
    },
    btnSubmitText: {fontSize: 16, color: '#FFF', fontWeight: '600'},

    dateModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 18,
    },
    dateModalCard: {
        width: '100%',
        backgroundColor: '#FFF',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 12,
    },
    dateModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E1E1E',
        marginBottom: 10,
    },
    dateModalInput: {
        height: 44,
        borderWidth: 1,
        borderColor: '#BFBFBF',
        borderRadius: 8,
        backgroundColor: '#F7F7F7',
        paddingHorizontal: 12,
        fontSize: 16,
        color: '#222',
    },
    dateModalError: {color: '#FF4D4F', fontSize: 12, marginTop: 6},
    dateQuickRow: {flexDirection: 'row', gap: 8, marginTop: 10},
    dateQuickButton: {
        flex: 1,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#EAF2FA',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateQuickText: {fontSize: 14, color: '#1E88E5', fontWeight: '600'},
    dateModalActions: {flexDirection: 'row', gap: 10, marginTop: 14},
    dateCancelButton: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#D7D7D7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateCancelText: {fontSize: 16, color: '#444', fontWeight: '600'},
    dateApplyButton: {
        flex: 1,
        height: 42,
        borderRadius: 10,
        backgroundColor: '#4CAF50',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateApplyText: {fontSize: 16, color: '#FFF', fontWeight: '700'},

    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBox: {
        width: '88%',
        backgroundColor: '#FFF',
        borderRadius: 18,
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 14,
    },
    modalTitle: {
        fontSize: 34,
        color: '#1E1E1E',
        textAlign: 'center',
        fontWeight: '700',
        marginBottom: 8,
    },
    modalMessage: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        marginBottom: 10,
    },
    modalDocTitle: {
        fontSize: 14,
        color: '#222',
        textAlign: 'center',
        fontWeight: '700',
        marginBottom: 10,
    },
    modalWarningWrap: {
        backgroundColor: '#FFE8E8',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 14,
    },
    modalWarningText: {
        fontSize: 13,
        color: '#FF6B6B',
        textAlign: 'center',
        fontWeight: '500',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    modalBtnGhost: {
        flex: 1,
        backgroundColor: '#D7D7D7',
        borderRadius: 10,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnGhostText: {color: '#444', fontSize: 18, fontWeight: '600'},
    modalBtnDanger: {
        flex: 1,
        backgroundColor: '#FF4A43',
        borderRadius: 10,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBtnDangerText: {color: '#FFF', fontSize: 18, fontWeight: '700'},
});

export default styles;
